export const mockProviders = [
  {
    id: '00000000-0000-4000-8000-000000000101',
    created_at: '2026-08-01T14:00:00.000Z',
    full_name: 'Jordan Sample',
    business_name: 'Sample Mobile Auto',
    phone: '5550101101',
    email: 'provider.one@example.test',
    state: 'Mississippi',
    city: 'Gulfport',
    zip_code: '39503',
    max_travel_radius: 45,
    max_travel_hours: 1,
    languages: ['English', 'Spanish'],
    years_experience: 8,
    specialties: ['General automotive mechanics', 'Electrical diagnostics', 'Gas vehicles'],
    vehicle_types_served: ['Car', 'Light truck'],
    vehicle_types_not_served: ['Heavy equipment'],
    services_not_offered: ['Paint'],
    no_advance_fee_acknowledged: true,
    application_status: 'Pending',
    account_status: 'Active',
    availability_status: 'Available',
    available_days: ['Monday', 'Tuesday', 'Saturday'],
    availability_schedule: {
      Monday: [{ start: '08:00', end: '17:00' }],
      Tuesday: [{ start: '08:00', end: '17:00' }],
      Saturday: [{ start: '09:00', end: '14:00' }],
    },
    scheduled_available: true,
    emergency_available: true,
    media_manifest: [
      { bucket: 'provider-private', path: 'mock://tools/toolbox.jpg', name: 'organized-tools.jpg', type: 'image/jpeg', category: 'tools' },
      { bucket: 'provider-private', path: 'mock://equipment/service-vehicle.jpg', name: 'service-vehicle.jpg', type: 'image/jpeg', category: 'equipment' },
      { bucket: 'provider-private', path: 'mock://work-1/diagnosis.jpg', name: 'electrical-diagnosis.jpg', type: 'image/jpeg', category: 'work_sample_1_photo', description: 'Diagnosed an intermittent no-start condition, repaired the damaged starter circuit, and verified reliable operation.', services: ['Electrical diagnostics', 'General automotive mechanics'] },
      { bucket: 'provider-private', path: 'mock://work-1/test.mp4', name: 'post-repair-test.mp4', type: 'video/mp4', category: 'work_sample_1_video', description: 'Diagnosed an intermittent no-start condition, repaired the damaged starter circuit, and verified reliable operation.', services: ['Electrical diagnostics', 'General automotive mechanics'] },
    ],
    certifications_manifest: [{ bucket: 'provider-private', path: 'mock://certifications/training.pdf', name: 'technical-training.pdf', type: 'application/pdf' }],
    internal_notes: '',
  },
  {
    id: '00000000-0000-4000-8000-000000000102',
    created_at: '2026-07-30T16:30:00.000Z',
    full_name: 'Taylor Demo',
    business_name: 'Demo Diesel Service',
    phone: '5550101102',
    email: 'provider.two@example.test',
    state: 'Louisiana',
    city: 'Slidell',
    zip_code: '70458',
    max_travel_radius: 60,
    max_travel_hours: 1.5,
    languages: ['English'],
    years_experience: 12,
    specialties: ['Diesel mechanics', 'Engine', 'Roadside assistance'],
    vehicle_types_served: ['Diesel truck', 'Heavy equipment'],
    vehicle_types_not_served: ['Electric vehicle'],
    services_not_offered: ['Bodywork', 'Paint'],
    no_advance_fee_acknowledged: false,
    application_status: 'Approved',
    account_status: 'Active',
    availability_status: 'Available',
    emergency_available: false,
    media_manifest: [],
    internal_notes: 'Synthetic record for local testing.',
  },
];

export const mockProviderProfiles = [
  {
    id: '00000000-0000-4000-8000-000000000113',
    created_at: '2026-07-30T16:30:00.000Z',
    full_name: 'Morgan Network Demo',
    business_name: 'Network Diagnostic Demo',
    phone: '5550101113',
    email: 'network.provider@example.test',
    state: 'Mississippi',
    city: 'Gulfport',
    zip_code: '39503',
    max_travel_radius: 50,
    max_travel_hours: 1,
    languages: ['English', 'Spanish'],
    specialties: ['General automotive mechanics', 'Electrical diagnostics'],
    vehicle_types_served: ['Car', 'Light truck'],
    vehicle_types_not_served: ['Heavy equipment'],
    services_offered: ['Diagnostics', 'Mechanical repair'],
    services_not_offered: ['Paint'],
    availability_status: 'Available',
    emergency_available: true,
    account_status: 'Active',
    compliance_score: 5,
    rotation_position: 1,
    application_id: null,
    user_id: null,
  },
];

export const mockCases = [
  {
    id: '00000000-0000-4000-8000-000000000201',
    created_at: '2026-08-02T15:10:00.000Z',
    case_number: 'CD-20260802-DEMO1',
    customer_name: 'Case Sample',
    phone: '5550102201',
    email: 'customer@example.test',
    email_verification_status: 'Verified',
    no_advance_payment_acknowledged: true,
    state: 'Mississippi',
    city: 'Gulfport',
    zip_code: '39503',
    street_address: '14035 Airport Road',
    approximate_location: '14035 Airport Road',
    vehicle_year: '2015',
    vehicle_make: 'Sample',
    vehicle_model: 'Sedan',
    vehicle_type: 'Car',
    fuel_type: 'Gasoline',
    problem_description: 'Synthetic no-start example for local testing.',
    vehicle_starts: 'No',
    vehicle_moves: 'No',
    service_requested: 'Diagnostics',
    specialty_needed: 'Electrical diagnostics',
    urgency: 'Immediate',
    preferred_language: 'English',
    share_consent: true,
    status: 'Pending review',
    assigned_provider_id: null,
    media_manifest: [],
    internal_notes: '',
  },
];

export const mockComplaints = [
  {
    id: '00000000-0000-4000-8000-000000000301',
    created_at: '2026-08-02T20:00:00.000Z',
    case_id: '00000000-0000-4000-8000-000000000201',
    case_number: 'CD-20260802-DEMO1',
    incident_type: 'Late communication',
    description: 'Synthetic complaint for local workflow testing.',
    requested_resolution: 'Contact update',
    severity: 'Normal',
    status: 'Open',
    media_manifest: [],
    internal_notes: '',
  },
];
